### ISSUE TITLE
Warning: "continue" targeting switch is equivalent to "break". 

### ISSUE THREAD

**Issue by klocus** [phplucidframe/phplucidframe#3]
Framework is not compatible with PHP 7.3 and 7.4

> Warning: "continue" targeting switch is equivalent to "break". ~ lib/classes/Validation.php on line 119

**Comment by cithukyaw** [comment]
@klocus Thanks for your info. We are trying to improve this framework to compatible with recent PHP versions.

**Comment by cithukyaw** [comment]
fixed in 3.0
